version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pgmain
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
